# FloatMask 常量定义
# 对应原 Java 项目 com.floatmask.constants.AppConstants.java


# 应用信息
APP_NAME = "FloatMask"
APP_PACKAGE = "com.floatmask"

# 悬浮框默认参数（像素）
DEFAULT_FLOATING_WIDTH = 400
DEFAULT_FLOATING_HEIGHT = 300
MIN_FLOATING_SIZE = 150
MAX_SIZE_RATIO = 0.9
MAX_HEIGHT_RATIO = 0.9
MIN_VISIBLE_RATIO = 0.2

# 悬浮框颜色（ARGB hex）
COLOR_TRANSPARENT_GRAY = 0x80757575
COLOR_TRANSPARENT_BLACK = 0x80000000
COLOR_SOLID_BLACK = 0xFF000000
COLORS = [COLOR_TRANSPARENT_GRAY, COLOR_TRANSPARENT_BLACK, COLOR_SOLID_BLACK]

# 手势参数
DOUBLE_TAP_TIMEOUT = 0.4
LONG_PRESS_TIMEOUT = 0.5
MIN_DRAG_DISTANCE = 5
RESIZE_AREA_SIZE = 80
LONG_PRESS_MOVE_TOLERANCE = 10

# 边缘吸附
EDGE_SNAP_THRESHOLD = 80
EDGE_SNAP_MARGIN = 0
EDGE_SNAP_ANIMATION_DURATION = 0.2

# 通知
NOTIFICATION_CHANNEL_ID = "floating_window_channel"
NOTIFICATION_CHANNEL_NAME = "悬浮窗服务"
NOTIFICATION_ID = 1

# SharedPreferences 键名
PREF_NAME = "floatmask_prefs"
PREF_KEY_X = "floating_x"
PREF_KEY_Y = "floating_y"
PREF_KEY_WIDTH = "floating_width"
PREF_KEY_HEIGHT = "floating_height"
PREF_KEY_COLOR = "floating_color"
PREF_KEY_ALPHA = "floating_alpha"
PREF_KEY_ENABLED = "service_enabled"
PREF_KEY_EDGE_SNAP = "edge_snap_enabled"
PREF_KEY_DEFAULT_COLOR = "default_color"
PREF_KEY_DEFAULT_ALPHA = "default_alpha"

# 请求码
REQUEST_CODE_OVERLAY_PERMISSION = 1001

# 广播动作
ACTION_UPDATE_SETTINGS = "com.floatmask.UPDATE_SETTINGS"
ACTION_UPDATE_COLOR = "com.floatmask.UPDATE_COLOR"
ACTION_UPDATE_ALPHA = "com.floatmask.UPDATE_ALPHA"
